name: Buildroot-CI

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      board:
        description: 'board'
        required: true
        default: 'qemu_x86_64'
      email-address:
        description: 'email-address'
        required: false
        default: ''
      custom-config:
        description: 'custom-config'
        required: false
        default: 'qemu_x86_64_defconfig'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

    - name: Board configure
      run: |
        echo "board: ${{ github.event.inputs.board }}"
        make ${{github.event.inputs.board}}_defconfig
        make source
        make toolchain

    - name: Run make
      run: |
        make -j8 2>&1 | tee build.log

    - name: Run buildcheck
      run: |
        tail -100 build.log
